import {test} from 'node:test';
import assert from 'node:assert/strict';
import {testDatabase, testEnvironment} from './fixtures.mjs';
import {REGISTERED_SERVICES,FINMIND_SERVICE,listToolDefinitions} from '../lib/service-registry.ts';
import {handleServiceCatalog,handleApi,handleMcp,TOOLS} from '../lib/mcp.ts';
const fake='fake-fixture-only-secret';
const headers={'content-type':'application/json','oai-authenticated-user-id':'owner-fixture','oai-authenticated-user-email':'owner@example.test'};
const env=testEnvironment(fake);
const request=(path='/api/services',h=headers,method='GET')=>new Request('https://site.test'+path,{method,headers:h});
test('registry has only approved FinMind endpoints and preserves exact MCP tool names',()=>{assert.deepEqual(REGISTERED_SERVICES.map(x=>x.id),['finmind']);assert.deepEqual(Object.values(FINMIND_SERVICE.endpoints).map(x=>x.url),['https://api.finmindtrade.com/api/v4/data','https://api.web.finmindtrade.com/v2/user_info']);assert.deepEqual(TOOLS,listToolDefinitions());assert.deepEqual(TOOLS.map(x=>x.name),['finmind_status','finmind_prices','finmind_usage','veilsplice_request']);assert.equal(JSON.stringify(REGISTERED_SERVICES).includes(fake),false);});
test('catalogue requires owner, refuses missing/bypass/client-only identity',async()=>{for(const h of [{},{'OAI-Sites-Authorization':'Bearer fake-platform-service-only'},{'x-user-email':'owner@example.test'},{...headers,'oai-authenticated-user-id':''}]){const r=await handleServiceCatalog(request('/api/services',h),env);assert.equal(r.status,401);assert.equal((await r.text()).includes(fake),false);}const r=await handleServiceCatalog(request('/api/services',{...headers,'oai-authenticated-user-email':'other@example.test'}),env);assert.equal(r.status,403);});
test('catalogue exposes only service ID and configured boolean, no arbitrary env values',async()=>{let r=await handleServiceCatalog(request(),{...env,UNRELATED_TOKEN:'never-return-this'});assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');assert.deepEqual(await r.json(),{ok:true,services:[{id:'finmind',configured:true}]});r=await handleServiceCatalog(request(),{...env,DB:testDatabase(null)});assert.deepEqual(await r.json(),{ok:true,services:[{id:'finmind',configured:false}]});});
test('catalogue rejects selectors, query injections, unsupported methods and origins',async()=>{for(const path of ['/api/services?secret=FINMIND_TOKEN','/api/services?provider=anything','/api/services?url=https://evil.test'])assert.equal((await handleServiceCatalog(request(path),env)).status,400);for(const path of ['/api/services/finmind','/api/services/FINMIND_TOKEN','/api/services/secret','/api/services/unknown'])assert.equal((await handleServiceCatalog(request(path),env)).status,404);for(const method of ['POST','PUT','DELETE'])assert.equal((await handleServiceCatalog(request('/api/services',headers,method),env)).status,405);assert.equal((await handleServiceCatalog(request('/api/services',{...headers,origin:'https://other.test'}),env)).status,403);});
test('existing FinMind API routes remain exact and unknown subroutes do not alias to a tool',async()=>{const e={...env,DB:testDatabase(null)};assert.equal((await handleApi(request('/api/finmind/status'),e)).status,200);for(const path of ['/api/finmind/unrelated/status','/api/finmind/unrelated/prices','/api/finmind/prices/extra','/api/finmind/secret'])assert.equal((await handleApi(request(path,headers,'POST'),e)).status,404);assert.equal((await handleApi(request('/api/finmind/status?secret=FINMIND_TOKEN'),e)).status,400);for(const tool of ['prices','usage']){const body=tool==='prices'?{stock_id:'2330',start_date:'2026-09-01',end_date:'2026-09-02'}:{};const r=await handleApi(new Request('https://site.test/api/finmind/'+tool,{method:'POST',headers,body:JSON.stringify(body)}),e);assert.equal((await r.json()).code,'NOT_CONFIGURED');}});
test('MCP discovery and missing-secret tool result survive registry refactor',async()=>{let r=await handleMcp(new Request('https://site.test/mcp',{method:'POST',headers,body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/list'})}),env);assert.deepEqual((await r.json()).result.tools,TOOLS);r=await handleMcp(new Request('https://site.test/mcp',{method:'POST',headers,body:JSON.stringify({jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'finmind_usage',arguments:{}}})}),{...env,DB:testDatabase(null)});assert.equal((await r.json()).result.structuredContent.code,'NOT_CONFIGURED');});

test('MCP initialization presents the shared VeilSplice product name',async()=>{const r=await handleMcp(new Request('https://site.test/mcp',{method:'POST',headers,body:JSON.stringify({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'fixture',version:'1'}}})}),env);const body=await r.json();assert.equal(body.result.serverInfo.name,'VeilSplice');assert.equal(body.result.serverInfo.version,'1.1.0');});
