"use client";
import { useCallback,useEffect,useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from "@/components/ui/table";
import { PRICE_SCHEMA, REGISTERED_SERVICES, FINMIND_SERVICE } from "@/lib/service-registry";
import CredentialSettings from "./credential-settings";
type Data={ok:boolean;configured?:boolean;message?:string;code?:string;rows?:Array<Record<string,string|number>>;user_count?:number;api_request_limit?:number};
function defaultRange(){const d=new Date();d.setDate(d.getDate()-1);const end=d.toISOString().slice(0,10);d.setDate(d.getDate()-14);return {start:d.toISOString().slice(0,10),end};}
async function loadStatus():Promise<Data>{try{const r=await fetch("/api/services",{cache:"no-store"});const data=await r.json() as {ok?:boolean;message?:string;services?:Array<{id:string;configured?:boolean}>};const service=Array.isArray(data.services)?data.services.find(item=>item.id===FINMIND_SERVICE.id):undefined;return data.ok&&typeof service?.configured==="boolean"?{ok:true,configured:service.configured}:{ok:false,message:data.message??"無法確認服務狀態。"};}catch{return {ok:false,message:"無法確認連線狀態，請重新整理。"};}}
type ModelContext={registerTool:(tool:{name:string;description:string;inputSchema:typeof PRICE_SCHEMA;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>Promise<Data>},options:{signal:AbortSignal})=>void|Promise<void>};
export default function Console(){
 const [state,setState]=useState<Data|null>(null),[result,setResult]=useState<Data|null>(null),[usage,setUsage]=useState<Data|null>(null),[busy,setBusy]=useState(false),[stock,setStock]=useState("2330"),[start,setStart]=useState(()=>defaultRange().start),[end,setEnd]=useState(()=>defaultRange().end);
 const refresh=useCallback(async()=>{setState(await loadStatus());},[]);
 useEffect(()=>{let active=true;void loadStatus().then(data=>{if(active)setState(data);});return()=>{active=false;};},[]);
 const run=useCallback(async(kind:"prices"|"usage",args:unknown)=>{setBusy(true);let data:Data;try{const r=await fetch(`/api/finmind/${kind}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(args)});data=await r.json();}catch{data={ok:false,message:"查詢未完成，請稍後再試。"};}if(kind==="prices")setResult(data);else setUsage(data);setBusy(false);return data;},[]);
 useEffect(()=>{const context=(document as Document & {modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;const life=new AbortController();try{Promise.resolve(context.registerTool({name:"read_finmind_prices",description:"Read up to 31 days of one stock's TaiwanStockPrice and display the same table as the page.",inputSchema:PRICE_SCHEMA,annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(value:unknown)=>{const input=value&&typeof value==="object"?value as Record<string,unknown>:{};setStock(typeof input?.stock_id==="string"?input.stock_id:"");setStart(typeof input?.start_date==="string"?input.start_date:"");setEnd(typeof input?.end_date==="string"?input.end_date:"");return run("prices",input);}},{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();},[run]);
 const ready=state?.ok&&state.configured;
 return <main className="shell"><header className="top"><div className="brand"><span className="mark" aria-hidden="true">V</span><div><p className="eyebrow">PRIVATE TOOL HUB</p><h1>VeilSplice 私人服務中心</h1></div></div><span className="privacy">同一入口 · 唯讀</span></header>
 <section className="service-catalog" aria-labelledby="catalog-title"><div className="catalog-heading"><div><h2 id="catalog-title">已加入的服務</h2><p>目前提供 FinMind。之後核准的服務會放在同一入口，各自保留固定的查詢範圍。</p></div><span className="limit">{REGISTERED_SERVICES.length} 個服務</span></div>
 {REGISTERED_SERVICES.map(service=><div className="service-card" key={service.id}><div className="service-heading"><div><h3>{service.name}</h3><p>{service.summary}</p></div><span className="service-status">{!state?"確認設定中…":!state.ok?"狀態無法確認":state.configured?"已設定":"未設定"}</span></div><ul className="tool-list">{service.tools.map(tool=><li key={tool.name}><span>{tool.title}</span><small>{tool.summary}</small></li>)}</ul></div>)}
 </section>
 <section className="connection" aria-labelledby="connection-title"><div><p className="eyebrow">FINMIND · 設定狀態</p><h2 id="connection-title">{!state?"確認設定中…":ready?"FinMind 金鑰已保存":state.ok?"FinMind 尚未設定或已停用":"需要確認存取權"}</h2><p>{!state?"正在確認此工具的設定。":state.message??(ready?"網頁與已連接工具共用後端設定，查詢時才連線至 FinMind。已保存不代表金鑰已通過 FinMind 驗證。":"請在下方由本人輸入並提交金鑰，讓網頁與已連接工具共用。")}</p></div><Button variant="outline" onClick={refresh}>重新檢查</Button></section>
 <CredentialSettings onChange={refresh}/>
 <div className="workspace"><section className="panel primary"><div className="section-title"><div><p className="eyebrow">TAIWAN STOCK PRICE</p><h2>台股每日行情</h2></div><span className="limit">最多 31 天</span></div>
 <form onSubmit={e=>{e.preventDefault();void run("prices",{stock_id:stock,start_date:start,end_date:end});}}><div className="fields"><label>股票代碼<Input value={stock} onChange={e=>setStock(e.target.value)} placeholder="2330" maxLength={7} pattern="[0-9]{4,6}[A-Z]?" required /></label><label>開始日期<Input type="date" value={start} onChange={e=>setStart(e.target.value)} required /></label><label>結束日期<Input type="date" value={end} onChange={e=>setEnd(e.target.value)} required /></label></div><div className="form-footer"><span>一次查詢一檔股票，日期含起訖日</span><Button disabled={busy||!ready} type="submit">{busy?"查詢中…":"查詢行情"}</Button></div></form>
 <div className="results" aria-live="polite">{!result?<div className="empty"><span className="empty-number">01—31</span><h3>選擇一段時間，開始研究</h3><p>資料來源為 FinMind，顯示開高低收與成交量。<br/>此處尚未查詢，不顯示示範行情。</p></div>:!result.ok?<div className="notice" role="alert">{result.message}</div>:!result.rows?.length?<div className="empty"><h3>這段日期沒有行情資料</h3><p>可能是非交易日，或資料來源尚未提供。</p></div>:<><p className="results-summary">{result.rows.length} 筆每日資料 · 成交量單位：股</p><Table><TableHeader><TableRow>{["日期","開盤","最高","最低","收盤","成交量"].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{result.rows.map(r=><TableRow key={r.date}><TableCell>{r.date}</TableCell>{["open","max","min","close","Trading_Volume"].map(k=><TableCell key={k}>{Number(r[k]).toLocaleString("zh-TW",{maximumFractionDigits:4})}</TableCell>)}</TableRow>)}</TableBody></Table></>}</div></section>
 <aside><section className="panel quota"><p className="eyebrow">API USAGE</p><h2>用量概況</h2><p>只讀取已使用次數與使用上限。</p>{usage?.ok?<div className="usage-value">{usage.user_count?.toLocaleString()}<span> / {usage.api_request_limit?.toLocaleString()}</span></div>:usage?<p className="notice" role="alert">{usage.message}</p>:<div className="usage-placeholder">尚未查詢</div>}<Button variant="outline" disabled={busy||!ready} onClick={()=>run("usage",{})}>查詢 API 用量</Button></section>
 <section className="boundaries endpoint-boundaries"><h3>FinMind 固定範圍</h3><ul className="endpoint-list">{Object.values(FINMIND_SERVICE.endpoints).map(endpoint=><li key={endpoint.url}><span>{endpoint.method} {endpoint.url}</span><small>{endpoint.scope}</small></li>)}</ul><ul><li>本工具最多每分鐘 12 次、每小時 120 次</li><li>不提供任意網址、資料集或帳戶內容查詢</li><li>金鑰只由伺服器使用，不儲存查詢結果</li></ul><a href="https://finmind.github.io/api_usage_count/" target="_blank" rel="noreferrer">FinMind 官方 API 說明</a></section></aside></div>
 <footer><span>Sites Worker adapter · 不等同於 Go VeilSplice 部署</span><span>資料僅供研究，可能延遲或修正</span></footer></main>;
}
